name: Compile ASP.NET

on:
  workflow_dispatch: 
  pull_request:
    types: [unlabeled, labeled, opened, synchronize, reopened]
    branches: [ milestone-2 ]

defaults:
    run:
      working-directory: server

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Check if PR is ready
      if: ${{contains(github.event.pull_request.labels.*.name, 'draft')}}
      uses: actions/github-script@v3
      with:
       script: |
        core.setFailed('PR is labeled draft')
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
